# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'coinpusher' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for coinpusher
pod 'NIMSDK', '4.4.0'
pod 'SSZipArchive', '~> 1.2'
pod 'Reachability', '~> 3.1.1'
pod 'CocoaLumberjack', '~> 2.0.0-rc2'
pod 'FMDB', '~>2.5' 

  target 'coinpusherTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'coinpusher-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for coinpusher-tvOS

  target 'coinpusher-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
